export const ALL_COURSE_REQUEST = "ALL_COURSE_REQUEST";
export const ALL_COURSE_SUCCESS = "ALL_COURSE_SUCCESS";
export const ALL_COURSE_FAIL = "ALL_COURSE_FAIL";

export const COURSE_DETAILS_REQUEST = "COURSE_DETAILS_REQUEST";
export const COURSE_DETAILS_SUCCESS = "COURSE_DETAILS_SUCCESS";
export const COURSE_DETAILS_FAIL = "COURSE_DETAILS_FAIL";

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_RESET = "CREATE_COURSE_RESET";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_RESET = "DELETE_COURSE_RESET";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_RESET = "UPDATE_COURSE_RESET";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";

export const CREATE_TRACK_REQUEST = "CREATE_TRACK_REQUEST";
export const CREATE_TRACK_SUCCESS = "CREATE_TRACK_SUCCESS";
export const CREATE_TRACK_RESET = "CREATE_TRACK_RESET";
export const CREATE_TRACK_FAIL = "CREATE_TRACK_FAIL";


export const UPDATE_TRACK_REQUEST = "UPDATE_TRACK_REQUEST";
export const UPDATE_TRACK_SUCCESS = "UPDATE_TRACK_SUCCESS";
export const UPDATE_TRACK_RESET = "UPDATE_TRACK_RESET";
export const UPDATE_TRACK_FAIL = "UPDATE_TRACK_FAIL";

export const DELETE_TRACK_REQUEST = "DELETE_TRACK_REQUEST";
export const DELETE_TRACK_SUCCESS = "DELETE_TRACK_SUCCESS";
export const DELETE_TRACK_RESET = "DELETE_TRACK_RESET";
export const DELETE_TRACK_FAIL = "DELETE_TRACK_FAIL";

export const TRACK_DETAILS_REQUEST = "TRACK_DETAILS_REQUEST";
export const TRACK_DETAILS_SUCCESS = "TRACK_DETAILS_SUCCESS";
export const TRACK_DETAILS_RESET = "TRACK_DETAILS_RESET";
export const TRACK_DETAILS_FAIL = "TRACK_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";